In [1]:
import numpy as np

Exercise 1 : Array Creation And Manipulation

Create a 1D NumPy array containing numbers from 0 to 9.

In [15]:
ar=np.array([range(0,10)])
print(ar)

[[0 1 2 3 4 5 6 7 8 9]]


 Exercise 2 : Type Conversion And Array Operations

 Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [14]:
l=[3.14, 2.17, 0, 1, 2]
list_to_ar=np.array(l,dtype=int)
print(ar)

[3 2 0 1 2]


Exercise 3 : Working With Multi-Dimensional Arrays

Create a 3x3 NumPy array with values ranging from 1 to 9.

In [11]:
ml_ar=np.array([range(1,10)]).reshape(3,3)
print(ml_ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 4 : Creating Multi-Dimensional Array With Random Numbers

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [12]:
md_ar=np.random.rand(4,5)
print(md_ar)

[[0.02858011 0.5678721  0.53424439 0.27071706 0.78947076]
 [0.43749736 0.43881335 0.57791784 0.26868041 0.78889567]
 [0.99310498 0.57188226 0.74035833 0.97137333 0.20553309]
 [0.23512439 0.31717736 0.20906136 0.20014283 0.90483207]]


Exercise 5 : Indexing Arrays

Select the second row from a given 2D NumPy array.

In [13]:
second_row=md_ar[1]
print(second_row)

[0.43749736 0.43881335 0.57791784 0.26868041 0.78889567]


Exercise 6 : Reversing Elements

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [16]:
reversed_ar=np.flip(ar)
print(reversed_ar)

[[9 8 7 6 5 4 3 2 1 0]]


Exercise 7 : Identity Matrix

Create a 4x4 identity matrix using NumPy.

In [17]:
im=np.eye(4)
print(im)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercise 8 : Simple Aggregate Funcs

Find the sum and average of a given 1D array.

In [19]:
sum_of_ar=np.sum(ar)
print("Sum: ", sum_of_ar)
avg_of_ar=np.mean(ar)
print("Average: ",avg_of_ar)

Sum:  45
Average:  4.5


Exercise 9 : Create Array And Change Its Structure

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [20]:
new_ar=np.array([range(1,21)]).reshape(4,5)
print(new_ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercise 10 : Conditional Selection Of Values

Extract all odd numbers from a given NumPy array.

In [21]:
odd_numbers=new_ar[new_ar%2==1]
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19]
